services:
  - type: web
    name: ged-backend
    env: node
    region: paris
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "ged_db"
      - key: DB_USER
        value: "render"
      - key: DB_PASSWORD
        value: ""
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-app.onrender.com
